#!/usr/bin/env python3
"""MDM command generator: builds an MDM command plist and writes it to stdout."""

import plistlib
import secrets
import sys
import uuid
from collections.abc import Callable
from dataclasses import dataclass, field
from pathlib import Path
from typing import NoReturn

# Values that can appear in an MDM command plist.
type _PlistValue = bool | int | str | bytes | list[_PlistValue] | dict[str, _PlistValue]

# Simple commands take no arguments; they are registered verbatim.
_SIMPLE_COMMANDS = [
    "ProfileList",
    "ProvisioningProfileList",
    "CertificateList",
    "SecurityInfo",
    "RestartDevice",
    "ShutDownDevice",
    "StopMirroring",
    "ClearRestrictionsPassword",
    "UserList",
    "LogOutUser",
    "PlayLostModeSound",
    "DisableLostMode",
    "DeviceLocation",
    "ManagedMediaList",
    "DeviceConfigured",
    "AvailableOSUpdates",
    "NSExtensionMappings",
    "OSUpdateStatus",
    "EnableRemoteDesktop",
    "DisableRemoteDesktop",
    "ActivationLockBypassCode",
    "ScheduleOSUpdateScan",
]

# Candidates for --random: read-only commands only.
_READ_ONLY_COMMANDS = [
    "SecurityInfo",
    "CertificateList",
    "ProfileList",
    "ProvisioningProfileList",
]


@dataclass
class _CommandArgs:
    """Parsed options for a single cmdr invocation."""

    uuid: str = field(default_factory=lambda: str(uuid.uuid4()))
    random: bool = False
    request_type: str | None = None
    query: list[str] = field(default_factory=list)
    mobileconfig: bytes = b""
    identifier: str = ""
    action: str = ""
    version: str = ""
    key: str = ""
    deferrals: int | None = None
    priority: str = ""
    fullname: str = ""
    username: str = ""
    lock: bool = False
    allowbst: bool = False
    pin: str = ""


def _print_usage() -> None:
    """Print the usage summary (previously generated by argparse)."""
    print(
        "MDM command generator\n"
        "Usage: cmdr.py [-u UUID] [-r] <command> [command options]\n"
        "\n"
        "Global options:\n"
        "  -u, --uuid UUID  command UUID (auto-generated if not specified)\n"
        "  -r, --random     select a random simple command "
        "(only non-argument commands)\n"
        "  -h, --help       show this help\n"
        "\n"
        "Simple commands (no arguments): " + ", ".join(_SIMPLE_COMMANDS) + "\n"
        "\n"
        "Commands with arguments:\n"
        "  DeviceInformation|DeviceInfo|DevInfo [QUERY ...]\n"
        "  InstallProfile <mobileconfig path>\n"
        "  RemoveProfile <identifier>\n"
        "  ScheduleOSUpdate <action> [--version V] [--key K] [--deferrals N] "
        "[--priority P]\n"
        "  AccountConfig [-f FULLNAME] [-u USERNAME] [-l]\n"
        "  Settings [--allowbst]\n"
        "  EraseDevice <pin>\n"
        "  DeviceLock <pin>\n"
        "  command <request_type>   arbitrary simple MDM command",
    )


def _die(message: str) -> NoReturn:
    """Print usage and exit with a usage-error status (argparse parity)."""
    print(f"error: {message}", file=sys.stderr)
    _print_usage()
    raise SystemExit(2)


def _expect_no_args(command: str, remainder: list[str]) -> None:
    """Reject leftover arguments for a command that takes none."""
    if remainder:
        _die(f"{command} takes no arguments, got: {' '.join(remainder)}")


def _expect_one_positional(command: str, remainder: list[str], name: str) -> str:
    """Return the single required positional argument of a command."""
    if len(remainder) != 1 or remainder[0].startswith("-"):
        _die(f"{command} requires exactly one {name} argument")
    return remainder[0]


# closure which generates a function that returns a simple command dictionary
def simple_command(
    request_type: str | None,
) -> Callable[[_CommandArgs], dict[str, _PlistValue]]:
    """Return a handler that builds a simple (no-argument) MDM command."""

    def simple_command_body(args: _CommandArgs) -> dict[str, _PlistValue]:
        nonlocal request_type
        if request_type is None:
            request_type = args.request_type
        if request_type is None:
            _die("no RequestType specified")
        return {"RequestType": request_type}

    return simple_command_body


def install_profile(args: _CommandArgs) -> dict[str, _PlistValue]:
    """Build an InstallProfile command with the mobileconfig payload."""
    return {
        "RequestType": "InstallProfile",
        "Payload": args.mobileconfig,
    }


def remove_profile(args: _CommandArgs) -> dict[str, _PlistValue]:
    """Build a RemoveProfile command for the given identifier."""
    return {
        "RequestType": "RemoveProfile",
        "Identifier": args.identifier,
    }


def dev_info(args: _CommandArgs) -> dict[str, _PlistValue]:
    """Build a DeviceInformation command with optional queries."""
    c: dict[str, _PlistValue] = {
        "RequestType": "DeviceInformation",
    }
    if args.query:
        c["Queries"] = args.query
    return c


def account_config(args: _CommandArgs) -> dict[str, _PlistValue]:
    """Build an AccountConfiguration command."""
    c: dict[str, _PlistValue] = {
        "RequestType": "AccountConfiguration",
    }
    if args.fullname:
        c["PrimaryAccountFullName"] = args.fullname
    if args.username:
        c["PrimaryAccountUserName"] = args.username
    if args.lock:
        c["LockPrimaryAccountInfo"] = True
    return c


def sched_update(args: _CommandArgs) -> dict[str, _PlistValue]:
    """Build a ScheduleOSUpdate command."""
    c: dict[str, _PlistValue] = {
        "RequestType": "ScheduleOSUpdate",
        "Updates": [{"InstallAction": args.action}],
    }
    updates = c["Updates"]
    if not isinstance(updates, list):
        _die("internal error: Updates is not a list")
    first_update = updates[0]
    if not isinstance(first_update, dict):
        _die("internal error: Updates entry is not a dict")
    if args.version:
        first_update["ProductVersion"] = args.version
    if args.key:
        first_update["ProductKey"] = args.key
    if args.deferrals:
        first_update["MaxUserDeferrals"] = args.deferrals
    if args.priority:
        first_update["Priority"] = args.priority
    return c


def settings(args: _CommandArgs) -> dict[str, _PlistValue]:
    """Build a Settings command."""
    c: dict[str, _PlistValue] = {"RequestType": "Settings", "Settings": []}
    if args.allowbst:
        c["Settings"] = [
            {
                "Item": "MDMOptions",
                "MDMOptions": {
                    "BootstrapTokenAllowed": True,
                },
            },
        ]
    return c


def make_erase_device_command(args: _CommandArgs) -> dict[str, _PlistValue]:
    """Build an EraseDevice command with the Find My PIN."""
    return {"RequestType": "EraseDevice", "PIN": args.pin}


def make_device_lock_command(args: _CommandArgs) -> dict[str, _PlistValue]:
    """Build a DeviceLock command with the six-character PIN."""
    return {"RequestType": "DeviceLock", "PIN": args.pin}


def _parse_sched_update(args: _CommandArgs, remainder: list[str]) -> None:
    """Fill ``args`` from the ScheduleOSUpdate remainder args."""
    if not remainder or remainder[0].startswith("-"):
        _die(
            "ScheduleOSUpdate requires an action (ex. InstallASAP, InstallLater, etc.)",
        )
    args.action = remainder[0]
    index = 1
    while index < len(remainder):
        arg = remainder[index]
        value = remainder[index + 1] if index + 1 < len(remainder) else None
        if arg == "--version" and value is not None:
            args.version = value
            index += 2
        elif arg == "--key" and value is not None:
            args.key = value
            index += 2
        elif arg == "--deferrals" and value is not None:
            try:
                args.deferrals = int(value)
            except ValueError:
                _die(f"--deferrals must be an integer, got: {value}")
            index += 2
        elif arg == "--priority" and value is not None:
            args.priority = value
            index += 2
        else:
            _die(f"invalid argument: {arg}")


def _parse_account_config(args: _CommandArgs, remainder: list[str]) -> None:
    """Fill ``args`` from the AccountConfig remainder args."""
    index = 0
    while index < len(remainder):
        arg = remainder[index]
        value = remainder[index + 1] if index + 1 < len(remainder) else None
        if arg in {"-f", "--fullname"} and value is not None:
            args.fullname = value
            index += 2
        elif arg in {"-u", "--username"} and value is not None:
            args.username = value
            index += 2
        elif arg in {"-l", "--lock"}:
            args.lock = True
            index += 1
        else:
            _die(f"invalid argument: {arg}")


def _command_handler(
    command: str,
    remainder: list[str],
    args: _CommandArgs,
) -> Callable[[_CommandArgs], dict[str, _PlistValue]]:
    """Resolve the command name to its handler, parsing its arguments."""
    if command in _SIMPLE_COMMANDS:
        _expect_no_args(command, remainder)
        return simple_command(command)
    if command in {"DeviceInformation", "DeviceInfo", "DevInfo"}:
        args.query = remainder
        return dev_info
    if command == "InstallProfile":
        mobileconfig_path = _expect_one_positional(
            command,
            remainder,
            "mobileconfig path",
        )
        try:
            args.mobileconfig = Path(mobileconfig_path).read_bytes()
        except OSError as exc:
            _die(f"cannot read mobileconfig file: {exc}")
        return install_profile
    if command == "RemoveProfile":
        args.identifier = _expect_one_positional(command, remainder, "identifier")
        return remove_profile
    if command == "ScheduleOSUpdate":
        _parse_sched_update(args, remainder)
        return sched_update
    if command == "AccountConfig":
        _parse_account_config(args, remainder)
        return account_config
    if command == "Settings":
        for arg in remainder:
            if arg == "--allowbst":
                args.allowbst = True
            else:
                _die(f"invalid argument: {arg}")
        return settings
    if command == "EraseDevice":
        args.pin = _expect_one_positional(command, remainder, "PIN")
        return make_erase_device_command
    if command == "DeviceLock":
        args.pin = _expect_one_positional(command, remainder, "PIN")
        return make_device_lock_command
    if command == "command":
        args.request_type = _expect_one_positional(command, remainder, "RequestType")
        return simple_command(None)
    _die(f"unknown MDM command: {command}")


def _parse_cli(
    argv: list[str],
) -> tuple[_CommandArgs, Callable[[_CommandArgs], dict[str, _PlistValue]]]:
    """Parse argv into command options plus the resolved command handler.

    NOTE (multi-agent, bead cosmos-main-jmg3): argparse e banned-api (TID251)
    no workspace; o parse manual zero-dependencia preserva o contrato da CLI
    (flags globais ate o primeiro posicional, depois parse por subcomando).

    Returns:
        Tuple of ``(args, handler)`` ready to build the command plist.
    """
    args = _CommandArgs()
    command: str | None = None
    remainder: list[str] = []
    index = 0
    while index < len(argv):
        arg = argv[index]
        if arg in {"-h", "--help"}:
            _print_usage()
            raise SystemExit(0)
        if arg in {"-u", "--uuid"} and index + 1 < len(argv):
            args.uuid = argv[index + 1]
            index += 2
        elif arg in {"-r", "--random"}:
            args.random = True
            index += 1
        elif arg.startswith("-"):
            _die(f"invalid argument: {arg}")
        else:
            command = arg
            remainder = argv[index + 1 :]
            break

    # command and random are mutually exclusive
    if command is not None and args.random:
        _die("--random cannot be combined with a command")
    if args.random:
        return args, simple_command(secrets.choice(_READ_ONLY_COMMANDS))
    if command is None:
        _die("no MDM command specified")
    return args, _command_handler(command, remainder, args)


def main() -> None:
    """Parse the CLI and write the resulting MDM command plist to stdout."""
    args, handler = _parse_cli(sys.argv[1:])
    c: dict[str, _PlistValue] = {
        "CommandUUID": args.uuid,
        "Command": handler(args),
    }
    plistlib.dump(c, sys.stdout.buffer)


if __name__ == "__main__":
    main()
